### ISSUE TITLE
libopencm3 framework updates

### ISSUE THREAD

**Issue by ofauchon** [platformio/builder-framework-libopencm3#4]
Hi, 

I use libopencm3 for a couple of PIO projects. 
It seems this framework was not recently updated and  libopencm3 code seems outdated. 

Do you plan to update it ? 

Do you have advices or solutions to fix this issue  ? 

Today, I'm not very confident with using PIO if frameworks are not properly maintained :-(

Thanks 
Olivier

**Comment by ivankravets** [comment]
Sorry, see https://github.com/platformio/builder-framework-libopencm3/pull/3

Yes, it's in our TODO and we plan to refactor integration with libopencm3 framework soon.

**Comment by ofauchon** [comment]
This is good a news!
I hope it' on the top of the TODO list :-) 

In thea meantime, you can try this  workaround :

** Clone and build latest libopencm3** 
$ cd /home/xxxxxxxx
$ git clone https://github.com/libopencm3/libopencm3.git
$ cd libopencm3 
$ make 

** Update PIO's framework-libopencm3**
$ cd ~/.platformio/packages/framework-libopencm3
$ mkdir old 
$ mv include lib old
$ ln -s /home/xxxxxxxx/dev/libopencm3/include include
$ ln -s /home/xxxxxxxx/dev/libopencm3/lib lib

... hope that help ! 

Olivier

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/builder-framework-libopencm3/commit/f59ffd84fe444c2a791644b1c72436ef7b86fbdf
